// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_KlIScPU14nlu3TU0_qAdw6mmElqEGQ',
    appId: '1:505077756834:web:7f6ee23db4c726c2c1b8fb',
    messagingSenderId: '505077756834',
    projectId: 'cmsc447-construction-inventory',
    authDomain: 'cmsc447-construction-inventory.firebaseapp.com',
    storageBucket: 'cmsc447-construction-inventory.firebasestorage.app',
    measurementId: 'G-WLX8KZPY1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP5NkWcyMlRzfA68YlN4CcBh-6bI1zECI',
    appId: '1:505077756834:android:87f05fb3687938acc1b8fb',
    messagingSenderId: '505077756834',
    projectId: 'cmsc447-construction-inventory',
    storageBucket: 'cmsc447-construction-inventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-2prQqDxMOIKS_rRPt4nMBpzZeMNmZ9k',
    appId: '1:505077756834:ios:f3d2543e819fbab7c1b8fb',
    messagingSenderId: '505077756834',
    projectId: 'cmsc447-construction-inventory',
    storageBucket: 'cmsc447-construction-inventory.firebasestorage.app',
    iosBundleId: 'com.example.constructionInventoryFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-2prQqDxMOIKS_rRPt4nMBpzZeMNmZ9k',
    appId: '1:505077756834:ios:f3d2543e819fbab7c1b8fb',
    messagingSenderId: '505077756834',
    projectId: 'cmsc447-construction-inventory',
    storageBucket: 'cmsc447-construction-inventory.firebasestorage.app',
    iosBundleId: 'com.example.constructionInventoryFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3_KlIScPU14nlu3TU0_qAdw6mmElqEGQ',
    appId: '1:505077756834:web:63569b7575dbeadec1b8fb',
    messagingSenderId: '505077756834',
    projectId: 'cmsc447-construction-inventory',
    authDomain: 'cmsc447-construction-inventory.firebaseapp.com',
    storageBucket: 'cmsc447-construction-inventory.firebasestorage.app',
    measurementId: 'G-H15CSF459N',
  );

}